import React from "react";
import { Link } from "react-router-dom";
import { Navbar, Footer } from "../../widgets";
import { ServiceLanding } from "./ServiceLanding.styles";

const UiUxDesign = () => (
  <><Navbar /><ServiceLanding $accent="#d64f78" $soft="#fff3f6">
    <div className="container hero"><div className="hero-copy"><span className="eyebrow">UI/UX design</span><h1>Interfaces that feel clear before they feel familiar.</h1><p>We translate user needs and business goals into focused digital experiences that are easy to understand, use and scale.</p><div className="hero-actions"><Link className="primary-link" to="/contact">Design with us <span>→</span></Link><Link className="text-link" to="/projects">See case studies</Link></div></div>
      <div className="hero-visual design-board" aria-hidden="true"><div className="board-tools"><b>Customer journey</b><span>Understand</span><span>Simplify</span><span className="active">Refine</span></div><div className="board-canvas"><div className="frame one"><i /><strong>Welcome back</strong><span /><span /><button>Continue</button></div><div className="frame two"><div /><div /><div /></div><div className="cursor">Ready</div></div></div>
    </div>
    <section className="section soft"><div className="container"><div className="section-heading"><div><span className="eyebrow">Our approach</span><h2>Understand people first. Design the right experience second.</h2></div><p>Every screen has a purpose. We clarify what customers need and remove the obstacles that stop them from moving forward.</p></div><div className="process-list">{[["01","Listen","Conversations and market review reveal what customers expect and where the current experience falls short."],["02","Organize","Content and important actions are arranged so people can find their way naturally."],["03","Explore","We show the experience early, making it easy to discuss and improve before production."],["04","Refine","The visual direction is polished into a clear, consistent and recognizable experience."],["05","Prepare","Every important screen and state is completed so the next stage can begin with confidence."]].map(x=><div className="process-row" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Design outcomes</span><h2>Useful at every stage of your product.</h2></div></div><div className="feature-grid">{[["Experience review","Find confusing moments and identify the improvements with the greatest customer impact."],["New service concept","Turn an early idea into a clear experience your team can understand and evaluate."],["Consistent visual language","Keep every page and customer interaction recognizable as the same business."],["Every screen considered","Make important journeys comfortable on phones, tablets and desktop devices."],["Preview before production","See and discuss how the experience works before committing to the final build."],["A clear plan forward","Receive a complete, organized direction that removes uncertainty from the next stage."]].map((x,i)=><article className="feature" key={x[0]}><span className="feature-index">0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
    <section className="section"><div className="container cta-band"><h2>Make your product easier to use and harder to forget.</h2><Link className="primary-link" to="/contact">Plan a design sprint <span>→</span></Link></div></section>
  </ServiceLanding><Footer /></>
);

export default UiUxDesign;
