const plansData = [
  {
    id: "basic",
    title: "Basic",
    description: "Single-page website (Landing Page)",
    price: "$300",
    buttonText: "Order now",
    features: [
      "Responsive design",
      "5 pages",
      "Domain and hosting setup",
      "Basic SEO optimization",
      "No custom design",
    ],
  },
  {
    id: "standard",
    title: "Standard",
    description: "Up to 5 pages with custom design",
    price: "$700",
    buttonText: "Order now",
    features: [
      "Unique design",
      "5 - 8 pages",
      "Domain and hosting setup",
      "Responsive design",
      "Contact form integration",
      "Basic SEO optimization",
      "Google Analytics setup",
    ],
  },
  {
    id: "optimal",
    title: "Optimal",
    description: "Up to 10 pages with advanced features",
    price: "$1200",
    buttonText: "Order now",
    features: [
      "Custom UI/UX design",
      "10 - 15 pages",
      "Domain and hosting setup",
      "Responsive design",
      "Contact form integration",
      "Advanced SEO optimization",
      "Integrations (CRM, payments, live chat)",
      "Blog / CMS setup",
      "Performance optimization",
    ],
  },
  {
    id: "premium",
    title: "Premium",
    description: "Custom development for business",
    price: "$2500",
    buttonText: "Order now",
    features: [
      "Unlimited number of pages",
      "Complex functionality (e-commerce, portals)",
      "6 months technical support",
      "Advanced SEO & analytics",
    ],
  },
];

export default plansData;
